## Reference: https://medium.com/platformer-blog/kubernetes-on-centos-7-with-firewalld-e7b53c1316af

- name: Opening basic Kubernets ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10255/tcp
    - 8472/udp

- name: Add masquerade
  firewalld:
    masquerade: enable
    permanent: yes
    state: enabled

- name: Expose NodePorts on control plane IP as well
  firewalld:
    port: 30000-32767/tcp
    permanent: yes
    state: enabled

- name: Restart firewalld
  systemd:
    name: firewalld
    daemon_reload: yes
    enabled: yes
    state: restarted
