# References:
# - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# - https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/

- name: Allow iptables (IPv4) to see bridged traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present

- name: Allow ip6tables (IPv6) to see bridged traffic
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present

- name: Set SELinux in permissive mode (effectively disabling it)
  selinux:
    policy: targeted
    state: permissive

- name: Adding yum repository for Kubernetes
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://yum.kubernetes.io/repos/kubernetes-el7-$basearch
    gpgkey: >
      https://yum.kubernetes.io/doc/yum-key.gpg
      https://yum.kubernetes.io/doc/rpm-package-key.gpg
    gpgcheck: true

- name: Install Kubernetes
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Configure node IP
  lineinfile:
    path: /etc/sysconfig/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: restarted
